version: "3.7"

services:

  mongodb:
    extends:
      file: docker-compose-dev.yml
      service: mongodb
    volumes:
      - mongo_data_lora:/data/db
  
  orion:
    extends:
      file: docker-compose-dev.yml
      service: orion
    command: -dbhost mongodb -port 1026 -logLevel INFO
  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: fiware-cygnus
    depends_on:
        - mongodb
    networks:
      - LoRaWAN
    expose:
        - "5080"
    ports:
        - "5051:5051"
        - "5080:5080"
    environment:
        - "CYGNUS_MONGO_HOSTS=mongodb:27017"
        - "CYGNUS_MONGO_SERVICE_PORT=5051"
        - "CYGNUS_LOG_LEVEL=DEBUG"
        - "CYGNUS_API_PORT=5080"
        - "CYGNUS_SERVICE_PORT=5051"
    volumes:
      - lora_device_data:/data/db
      
  iotagent-lora:
    depends_on:
      - orion
      - mongodb
    entrypoint: bin/iotagent-lora docker/config-docker.js
    hostname: iotagent-lora
    image: ioeari/iotagent-lora
    ports:
      - "4041:4041"
    networks:
      - LoRaWAN
    
volumes:
  mongo_data_lora: 
  lora_device_data: 

networks:
  LoRaWAN: {}
